# -*- coding: utf-8 -*-
"""weather

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1leaYwmSguqz8BmoXzsgcfrMqeBO_sUtO
"""

import requests
import json
from datetime import datetime

# TODO: Replace with your actual API key from OpenWeatherMap
API_KEY = "c19fcacd867c5f39237be0bd0c53a49c"
BASE_URL = "http://api.openweathermap.org/data/2.5/weather"


def get_weather(city):
    """
    Fetch current weather data for a given city.

    Args:
        city (str): Name of the city

    Returns:
        dict: Weather data or None if error occurs
    """
    try:
        # Build the complete URL with parameters
        params = {
            'q': city,
            'appid': API_KEY,
            'units': 'metric'  # Use Celsius
        }

        # Make API request
        response = requests.get(BASE_URL, params=params)
        response.raise_for_status()  # Raise error for bad status codes

        data = response.json()

        # Extract relevant information
        weather_info = {
            'city': data['name'],
            'country': data['sys']['country'],
            'temperature': data['main']['temp'],
            'feels_like': data['main']['feels_like'],
            'humidity': data['main']['humidity'],
            'description': data['weather'][0]['description'],
            'wind_speed': data['wind']['speed'],
            'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        }

        return weather_info

    except requests.exceptions.RequestException as e:
        print(f"Error fetching weather for {city}: {e}")
        return None
    except KeyError as e:
        print(f"Error parsing weather data: {e}")
        return None


def display_weather(weather_data):
    """
    Display weather information in a formatted way.

    Args:
        weather_data (dict): Weather information
    """
    if weather_data is None:
        print("No weather data to display.")
        return

    print("\n" + "="*50)
    print(f"Weather in {weather_data['city']}, {weather_data['country']}")
    print("="*50)
    print(f"Temperature: {weather_data['temperature']}°C")
    print(f"Feels Like: {weather_data['feels_like']}°C")
    print(f"Humidity: {weather_data['humidity']}%")
    print(f"Conditions: {weather_data['description'].title()}")
    print(f"Wind Speed: {weather_data['wind_speed']} m/s")
    print(f"Time: {weather_data['timestamp']}")
    print("="*50 + "\n")


def save_to_file(weather_data, filename='weather_data.json'):
    """
    Save weather data to a JSON file.

    Args:
        weather_data (dict): Weather information
        filename (str): Name of file to save to
    """
    if weather_data is None:
        return

    try:
        # Try to load existing data
        try:
            with open(filename, 'r') as f:
                all_data = json.load(f)
        except FileNotFoundError:
            all_data = []

        # Append new data
        all_data.append(weather_data)

        # Save back to file
        with open(filename, 'w') as f:
            json.dump(all_data, f, indent=2)

        print(f"✓ Data saved to {filename}")

    except Exception as e:
        print(f"Error saving data: {e}")


def main():
    """Main program loop."""
    print(" Welcome to Weather Data Analyzer!")
    print("="*50)

    while True:
        print("\nOptions:")
        print("1. Check weather for a city")
        print("2. Exit")

        choice = input("\nEnter your choice (1-2): ").strip()

        if choice == '1':
            city = input("Enter city name: ").strip()
            if city:
                print(f"\nFetching weather for {city}...")
                weather = get_weather(city)
                display_weather(weather)

                # Ask if user wants to save
                save = input("Save this data? (y/n): ").strip().lower()
                if save == 'y':
                    save_to_file(weather)
            else:
                print("Please enter a valid city name.")

        elif choice == '2':
            print("\nThanks for using Weather Analyzer! ")
            break
        else:
            print("Invalid choice. Please enter 1 or 2.")


if __name__ == "__main__":
    main()